<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container92T9lxJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container92T9lxJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container92T9lxJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container92T9lxJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container92T9lxJ\App_KernelDevDebugContainer([
    'container.build_hash' => '92T9lxJ',
    'container.build_id' => '78d00697',
    'container.build_time' => 1608820822,
], __DIR__.\DIRECTORY_SEPARATOR.'Container92T9lxJ');
