<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWjCOjr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWjCOjr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWjCOjr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWjCOjr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFWjCOjr\App_KernelDevDebugContainer([
    'container.build_hash' => 'FWjCOjr',
    'container.build_id' => '7e08aa4d',
    'container.build_time' => 1608811168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWjCOjr');
