<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkDjdkI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkDjdkI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkDjdkI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkDjdkI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkDjdkI\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkDjdkI',
    'container.build_id' => '4695f6d4',
    'container.build_time' => 1608902740,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkDjdkI');
