<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\FrontEndController::index'], [], [['text', '/']], [], []],
    'test' => [['age'], ['age' => '0', '_controller' => 'App\\Controller\\FrontEndController::test'], ['age' => '\\d+'], [['variable', '/', '\\d+', 'age', true], ['text', '/test']], [['text', '127.0.0.1']], ['https', 'http']],
    'hello' => [['prenom'], ['prenom' => 'World', '_controller' => 'App\\Controller\\FrontEndController::hello'], [], [['variable', '/', '[^/]++', 'prenom', true], ['text', '/hello']], [], []],
    'createapp' => [[], ['_controller' => 'App\\Controller\\FrontEndController::createApp'], [], [['text', '/createapp']], [], []],
];
