<?php

namespace Container71WUDTA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5LCxdwBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5LCxdwB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5LCxdwB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appsR' => ['privates', 'App\\Repository\\AppsRepository', 'getAppsRepositoryService', true],
        ], [
            'appsR' => 'App\\Repository\\AppsRepository',
        ]);
    }
}
