# index:
#   path: /
#   controller: App\Controller\TestController::index

# test:
#   path: /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET, POST]
#   host: 127.0.0.1
#   schemes: [https, http]
#   # api.applipro.fr / www.applipro.fr / applipro.fr
#   # defaults:
#   #   age: 0
#   # requirements:
#   #   age: \d+
